/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_api_v1_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_api_v1_companies__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{symbol}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Prices */
        get: operations["get_company_prices_api_v1_companies__symbol__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{symbol}/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Scores */
        get: operations["get_company_scores_api_v1_companies__symbol__scores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screener": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screen */
        get: operations["screen_api_v1_screener_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CategoryBreakdown */
        CategoryBreakdown: {
            /** Category */
            category: string;
            /** Score */
            score: number | null;
            /** Factors */
            factors: components["schemas"]["FactorBreakdownItem"][];
        };
        /** CategoryScores */
        CategoryScores: {
            /** Financial Health */
            financial_health?: number | null;
            /** Growth */
            growth?: number | null;
            /** Value */
            value?: number | null;
            /** Quality */
            quality?: number | null;
            /** Profitability */
            profitability?: number | null;
            /** Momentum */
            momentum?: number | null;
            /** Volatility */
            volatility?: number | null;
            /** Risk */
            risk?: number | null;
        };
        /** CompanyDetail */
        CompanyDetail: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Industry */
            industry: string | null;
            /** Exchange */
            exchange: string | null;
            /** Market Cap */
            market_cap: string | null;
            /** Universe */
            universe: string;
            /** Is Active */
            is_active: boolean;
        };
        /** CompanyList */
        CompanyList: {
            /** Items */
            items: components["schemas"]["CompanySummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** CompanyScoreDetail */
        CompanyScoreDetail: {
            /** Symbol */
            symbol: string;
            /** Profile */
            profile: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Composite */
            composite: number | null;
            /** Data Completeness */
            data_completeness: number;
            /** Engine Version */
            engine_version: string;
            categories: components["schemas"]["CategoryScores"];
            /** Breakdown */
            breakdown: components["schemas"]["CategoryBreakdown"][];
        };
        /** CompanySummary */
        CompanySummary: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Industry */
            industry: string | null;
        };
        /** FactorBreakdownItem */
        FactorBreakdownItem: {
            /** Factor */
            factor: string;
            /** Raw */
            raw: number | null;
            /** Score */
            score: number | null;
            /** Inverse */
            inverse: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db */
            db: string;
            /** Environment */
            environment: string;
        };
        /** PricePoint */
        PricePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Close */
            close: string;
            /** Adj Close */
            adj_close: string;
            /** Volume */
            volume: number;
        };
        /** PriceSeries */
        PriceSeries: {
            /** Symbol */
            symbol: string;
            /** Range */
            range: string;
            /** Points */
            points: components["schemas"]["PricePoint"][];
        };
        /** ScreenerResponse */
        ScreenerResponse: {
            /** Items */
            items: components["schemas"]["ScreenerRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Profile */
            profile: string;
            /** As Of */
            as_of: string | null;
        };
        /** ScreenerRow */
        ScreenerRow: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Composite */
            composite: number | null;
            /** Data Completeness */
            data_completeness: number;
            categories: components["schemas"]["CategoryScores"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_companies_api_v1_companies_get: {
        parameters: {
            query?: {
                /** @description symbol or name substring */
                query?: string | null;
                sector?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_v1_companies__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_prices_api_v1_companies__symbol__prices_get: {
        parameters: {
            query?: {
                /** @description one of 1M, 3M, 6M, 1Y, 2Y, 5Y, MAX */
                range?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_scores_api_v1_companies__symbol__scores_get: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyScoreDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screen_api_v1_screener_get: {
        parameters: {
            query?: {
                profile?: string;
                minScore?: number | null;
                sector?: string | null;
                sortBy?: string;
                order?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
