/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_api_v1_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_api_v1_companies__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{symbol}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Prices */
        get: operations["get_company_prices_api_v1_companies__symbol__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{symbol}/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Scores */
        get: operations["get_company_scores_api_v1_companies__symbol__scores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screener": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screen */
        get: operations["screen_api_v1_screener_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rankings */
        get: operations["rankings_api_v1_strategy_rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/regime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Regime */
        get: operations["regime_api_v1_strategy_regime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategy/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decisions */
        get: operations["decisions_api_v1_strategy_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio */
        get: operations["portfolio_api_v1_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Schedule
         * @description When the next decision cycle runs, and whether a worker is alive to run it.
         */
        get: operations["schedule_api_v1_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance */
        get: operations["performance_api_v1_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtests */
        get: operations["list_backtests_api_v1_backtests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backtest Detail */
        get: operations["backtest_detail_api_v1_backtests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Health */
        get: operations["system_health_api_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestDetail */
        BacktestDetail: {
            summary: components["schemas"]["BacktestSummary"];
            /** Equity Curve */
            equity_curve: components["schemas"]["BacktestEquityPoint"][];
            /** Trades */
            trades: components["schemas"]["BacktestTradeRow"][];
        };
        /** BacktestEquityPoint */
        BacktestEquityPoint: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Equity */
            equity: number;
            /** Regime */
            regime: string;
        };
        /** BacktestSummary */
        BacktestSummary: {
            /** Id */
            id: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Config Version */
            config_version: string;
            /** Universe Size */
            universe_size: number;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BacktestTradeRow */
        BacktestTradeRow: {
            /** Symbol */
            symbol: string;
            /** Side */
            side: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Shares */
            shares: number;
            /** Price */
            price: number;
            /** Reason */
            reason: string;
            /** Realized Pnl */
            realized_pnl: number;
        };
        /** CategoryBreakdown */
        CategoryBreakdown: {
            /** Category */
            category: string;
            /** Score */
            score: number | null;
            /** Factors */
            factors: components["schemas"]["FactorBreakdownItem"][];
        };
        /** CategoryScores */
        CategoryScores: {
            /** Financial Health */
            financial_health?: number | null;
            /** Growth */
            growth?: number | null;
            /** Value */
            value?: number | null;
            /** Quality */
            quality?: number | null;
            /** Profitability */
            profitability?: number | null;
            /** Momentum */
            momentum?: number | null;
            /** Volatility */
            volatility?: number | null;
            /** Risk */
            risk?: number | null;
        };
        /** CompanyDetail */
        CompanyDetail: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Industry */
            industry: string | null;
            /** Exchange */
            exchange: string | null;
            /** Market Cap */
            market_cap: string | null;
            /** Universe */
            universe: string;
            /** Is Active */
            is_active: boolean;
        };
        /** CompanyList */
        CompanyList: {
            /** Items */
            items: components["schemas"]["CompanySummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** CompanyScoreDetail */
        CompanyScoreDetail: {
            /** Symbol */
            symbol: string;
            /** Profile */
            profile: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Composite */
            composite: number | null;
            /** Data Completeness */
            data_completeness: number;
            /** Engine Version */
            engine_version: string;
            categories: components["schemas"]["CategoryScores"];
            /** Breakdown */
            breakdown: components["schemas"]["CategoryBreakdown"][];
        };
        /** CompanySummary */
        CompanySummary: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Industry */
            industry: string | null;
        };
        /** DecisionRow */
        DecisionRow: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Cycle Id */
            cycle_id: string;
            /** Symbol */
            symbol: string;
            /** Action */
            action: string;
            /** Reason */
            reason: string;
            /** Regime */
            regime: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
        };
        /** EquityPoint */
        EquityPoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Equity */
            equity: number;
            /** Cash */
            cash: number;
            /** Regime */
            regime: string;
            /** Positions */
            positions: number;
        };
        /** FactorBreakdownItem */
        FactorBreakdownItem: {
            /** Factor */
            factor: string;
            /** Raw */
            raw: number | null;
            /** Score */
            score: number | null;
            /** Inverse */
            inverse: boolean;
        };
        /** FeedFreshness */
        FeedFreshness: {
            /** Feed */
            feed: string;
            /** As Of */
            as_of: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db */
            db: string;
            /** Environment */
            environment: string;
        };
        /** JobRunRow */
        JobRunRow: {
            /** Job Name */
            job_name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Status */
            status: string;
            /** Records Processed */
            records_processed: number | null;
            /** Error */
            error: string | null;
        };
        /** PerformanceResponse */
        PerformanceResponse: {
            /** Points */
            points: components["schemas"]["EquityPoint"][];
            /** Spy */
            spy: number[];
            /** Start Equity */
            start_equity: number | null;
            /** Total Return */
            total_return: number | null;
            /** Spy Return */
            spy_return: number | null;
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            /** Ts */
            ts: string | null;
            /** Equity */
            equity: number | null;
            /** Cash */
            cash: number | null;
            /** Regime */
            regime: string | null;
            /** Positions */
            positions: components["schemas"]["PositionRow"][];
        };
        /** PositionRow */
        PositionRow: {
            /** Symbol */
            symbol: string;
            /** Shares */
            shares: number;
            /** Avg Entry Price */
            avg_entry_price: number;
            /** Stop Price */
            stop_price: number | null;
            /** Target Price */
            target_price: number | null;
            /** Entry Composite */
            entry_composite: number | null;
        };
        /** PricePoint */
        PricePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Close */
            close: string;
            /** Adj Close */
            adj_close: string;
            /** Volume */
            volume: number;
        };
        /** PriceSeries */
        PriceSeries: {
            /** Symbol */
            symbol: string;
            /** Range */
            range: string;
            /** Points */
            points: components["schemas"]["PricePoint"][];
        };
        /** RankingRow */
        RankingRow: {
            /** Rank */
            rank: number | null;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Composite */
            composite: number | null;
            /** Composite Percentile */
            composite_percentile?: number | null;
            families: components["schemas"]["StrategyFamilies"];
            /** Data Completeness */
            data_completeness: number;
        };
        /** RankingsResponse */
        RankingsResponse: {
            /** Ts */
            ts: string | null;
            /** Regime */
            regime: string | null;
            /** Items */
            items: components["schemas"]["RankingRow"][];
        };
        /** RegimeResponse */
        RegimeResponse: {
            /** Ts */
            ts: string | null;
            /** Label */
            label: string | null;
            /** Raw Label */
            raw_label: string | null;
            /** Bearish Count */
            bearish_count: number | null;
            /** Features */
            features: {
                [key: string]: unknown;
            } | null;
            /** Weights */
            weights: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ScheduleResponse
         * @description Next decision cycle, plus whether a worker is actually around to run it.
         */
        ScheduleResponse: {
            /** Next Cycle At */
            next_cycle_at: string | null;
            /** Interval Minutes */
            interval_minutes: number;
            /** Cycle Window Et */
            cycle_window_et: string;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /** Worker Last Seen */
            worker_last_seen: string | null;
            /** Worker Running */
            worker_running: boolean;
            /** Market Hours */
            market_hours: boolean;
        };
        /** ScreenerResponse */
        ScreenerResponse: {
            /** Items */
            items: components["schemas"]["ScreenerRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Profile */
            profile: string;
            /** As Of */
            as_of: string | null;
        };
        /** ScreenerRow */
        ScreenerRow: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Composite */
            composite: number | null;
            /** Data Completeness */
            data_completeness: number;
            categories: components["schemas"]["CategoryScores"];
        };
        /** StrategyFamilies */
        StrategyFamilies: {
            /** Valuation */
            valuation?: number | null;
            /** Fundamentals */
            fundamentals?: number | null;
            /** Momentum */
            momentum?: number | null;
            /** Technical */
            technical?: number | null;
            /** Risk */
            risk?: number | null;
        };
        /** SystemHealthResponse */
        SystemHealthResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobRunRow"][];
            /** Feeds */
            feeds: components["schemas"]["FeedFreshness"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_companies_api_v1_companies_get: {
        parameters: {
            query?: {
                /** @description symbol or name substring */
                query?: string | null;
                sector?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_v1_companies__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_prices_api_v1_companies__symbol__prices_get: {
        parameters: {
            query?: {
                /** @description one of 1M, 3M, 6M, 1Y, 2Y, 5Y, MAX */
                range?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_scores_api_v1_companies__symbol__scores_get: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyScoreDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screen_api_v1_screener_get: {
        parameters: {
            query?: {
                profile?: string;
                minScore?: number | null;
                sector?: string | null;
                sortBy?: string;
                order?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rankings_api_v1_strategy_rankings_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regime_api_v1_strategy_regime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeResponse"];
                };
            };
        };
    };
    decisions_api_v1_strategy_decisions_get: {
        parameters: {
            query?: {
                limit?: number;
                action?: string | null;
                symbol?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_api_v1_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
        };
    };
    schedule_api_v1_schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"];
                };
            };
        };
    };
    performance_api_v1_performance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceResponse"];
                };
            };
        };
    };
    list_backtests_api_v1_backtests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestSummary"][];
                };
            };
        };
    };
    backtest_detail_api_v1_backtests__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_health_api_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemHealthResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
