"""market data tables

Revision ID: 437b1630452a
Revises: 0001
Create Date: 2026-07-25 12:23:21.944936
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmarks',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('companies',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('universe', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('delisted_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('ix_companies_active_universe', 'companies', ['is_active', 'universe'], unique=False)
    op.create_index('ix_companies_sector', 'companies', ['sector'], unique=False)
    op.create_table('benchmark_prices',
    sa.Column('benchmark_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('benchmark_id', 'date')
    )
    op.create_table('prices_daily',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'date')
    )
    # BRIN indexes: prices are append-mostly and physically clustered by date,
    # so a block-range index gives cheap range scans at a fraction of a B-tree's size.
    op.create_index(
        'ix_prices_daily_date_brin', 'prices_daily', ['date'],
        unique=False, postgresql_using='brin',
    )
    op.create_index(
        'ix_benchmark_prices_date_brin', 'benchmark_prices', ['date'],
        unique=False, postgresql_using='brin',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices_daily')
    op.drop_table('benchmark_prices')
    op.drop_index('ix_companies_sector', table_name='companies')
    op.drop_index('ix_companies_active_universe', table_name='companies')
    op.drop_table('companies')
    op.drop_table('benchmarks')
    # ### end Alembic commands ###
