"""fundamentals and research scores

Revision ID: c96588ca879a
Revises: 0002
Create Date: 2026-07-25 14:04:34.474456
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamentals',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=4), nullable=False),
    sa.Column('fiscal_date', sa.Date(), nullable=False),
    sa.Column('reported_at', sa.Date(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('eps_diluted', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('interest_expense', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('current_liabilities', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('cash', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('equity', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('shares_out', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('operating_cf', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('capex', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period', 'fiscal_date', name='uq_fundamentals_period')
    )
    op.create_index('ix_fundamentals_company_date', 'fundamentals', ['company_id', 'fiscal_date'], unique=False)
    op.create_table('research_scores',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('profile', sa.String(length=16), nullable=False),
    sa.Column('financial_health', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('growth', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('value', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('quality', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('profitability', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('momentum', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('risk', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('composite', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('data_completeness', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'as_of_date', 'profile', name='uq_scores_asof')
    )
    op.create_index('ix_scores_asof_composite', 'research_scores', ['as_of_date', 'composite'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_asof_composite', table_name='research_scores')
    op.drop_table('research_scores')
    op.drop_index('ix_fundamentals_company_date', table_name='fundamentals')
    op.drop_table('fundamentals')
    # ### end Alembic commands ###
