"""fundamentals ebit and estimates

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-25 16:15:02.288939
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimates',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('forward_eps', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('forward_pe', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('peg', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'as_of_date', name='uq_estimates_asof')
    )
    op.create_index('ix_estimates_company_date', 'estimates', ['company_id', 'as_of_date'], unique=False)
    op.add_column('fundamentals', sa.Column('ebit', sa.Numeric(precision=24, scale=4), nullable=True))
    op.add_column('fundamentals', sa.Column('operating_income', sa.Numeric(precision=24, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamentals', 'operating_income')
    op.drop_column('fundamentals', 'ebit')
    op.drop_index('ix_estimates_company_date', table_name='estimates')
    op.drop_table('estimates')
    # ### end Alembic commands ###
