"""regime strategy scores config

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-25 16:31:24.958236
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regime_snapshots',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('raw_label', sa.String(length=16), nullable=False),
    sa.Column('bearish_count', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_regime_ts', 'regime_snapshots', ['ts'], unique=False)
    op.create_table('strategy_config',
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_strategy_config_version')
    )
    op.create_table('strategy_scores',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('regime', sa.String(length=16), nullable=False),
    sa.Column('valuation', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('fundamentals', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('momentum', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('technical', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('risk', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('composite', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('data_completeness', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('weights_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'ts', name='uq_strategy_scores_ts')
    )
    op.create_index('ix_strategy_scores_ts_composite', 'strategy_scores', ['ts', 'composite'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategy_scores_ts_composite', table_name='strategy_scores')
    op.drop_table('strategy_scores')
    op.drop_table('strategy_config')
    op.drop_index('ix_regime_ts', table_name='regime_snapshots')
    op.drop_table('regime_snapshots')
    # ### end Alembic commands ###
