"""trading tables

Revision ID: 0008
Revises: 0007
Create Date: 2026-07-26 09:42:57.374224
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('client_order_id', sa.UUID(), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('reject_reason', sa.String(length=200), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', name='uq_orders_client_id')
    )
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('positions', sa.Integer(), nullable=False),
    sa.Column('regime', sa.String(length=16), nullable=False),
    sa.Column('holdings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts', name='uq_portfolio_snapshot_ts')
    )
    op.create_table('position_theses',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('atr_at_entry', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('entry_composite', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('entry_fundamentals_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('took_partial', sa.Boolean(), nullable=False),
    sa.Column('highest_close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reversal_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_thesis_symbol')
    )
    op.create_table('trade_decisions',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('regime', sa.String(length=16), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_decisions_cycle', 'trade_decisions', ['cycle_id'], unique=False)
    op.create_index('ix_trade_decisions_ts_symbol', 'trade_decisions', ['ts', 'symbol'], unique=False)
    op.create_table('executions',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('broker_execution_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('fill_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_execution_id', name='uq_exec_broker_id')
    )
    op.create_index('ix_executions_order', 'executions', ['order_id'], unique=False)
    op.create_table('positions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_positions_symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_index('ix_executions_order', table_name='executions')
    op.drop_table('executions')
    op.drop_index('ix_trade_decisions_ts_symbol', table_name='trade_decisions')
    op.drop_index('ix_trade_decisions_cycle', table_name='trade_decisions')
    op.drop_table('trade_decisions')
    op.drop_table('position_theses')
    op.drop_table('portfolio_snapshots')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
